global:
  scrape_interval: 5s  # Interroge les cibles toutes les 5 secondes

scrape_configs:
  - job_name: "fastapi"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["api:8000"]  # Nom du service FastAPI dans Docker
